# Generated by Django 4.2.4 on 2023-08-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotareas',
            name='id_tarea',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
