# Generated by Django 4.2.3 on 2023-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_registrotareas_asignado_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Mediana'), ('baja', 'Baja')], default='media', max_length=10)),
            ],
        ),
    ]
