# Generated by Django 4.2.3 on 2023-09-06 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotareas',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.prioridad'),
        ),
    ]
